version: '3.3'
services:
  db:
    image: mysql:8.0
    volumes:
      - ./mysql-dump:/docker-entrypoint-initdb.d:rw
      - ./mysql-data:/var/lib/mysql:rw
      - ./wait-for-mysql-started.sh:/wait-for-mysql-started.sh:ro
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: socialmediaapp
  web:
    ports:
      - "127.0.0.1:8080:8080"
    depends_on:
      - db
    image: tomcat
    volumes:
      - /root/toeic-app-01/stream:/root/toeic-app-01/stream
      - ./Toeic.war:/usr/local/tomcat/webapps/Toeic.war:ro
      - ./localstorage:/root/toeic-app-01/storage
